version: '3.8'
services:
  c-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.c
    volumes:
      - .:/app
    command: "/bin/sh -c 'make clean && make all && ./eval3_c'"

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    volumes:
      - .:/app
    ports:
      - "8888:8888"
